// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/Internal.proto

package binary.wz.im.common.proto;

public final class Internal {
  private Internal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InternalMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:binary.wz.im.common.proto.InternalMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *协议版本号
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <pre>
     *协议版本号
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <pre>
     *消息标识
     * </pre>
     *
     * <code>required string id = 2;</code>
     */
    boolean hasId();
    /**
     * <pre>
     *消息标识
     * </pre>
     *
     * <code>required string id = 2;</code>
     */
    java.lang.String getId();
    /**
     * <pre>
     *消息标识
     * </pre>
     *
     * <code>required string id = 2;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     *消息序号
     * </pre>
     *
     * <code>optional int64 seq = 3;</code>
     */
    boolean hasSeq();
    /**
     * <pre>
     *消息序号
     * </pre>
     *
     * <code>optional int64 seq = 3;</code>
     */
    long getSeq();

    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>optional string fromId = 4;</code>
     */
    boolean hasFromId();
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>optional string fromId = 4;</code>
     */
    java.lang.String getFromId();
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>optional string fromId = 4;</code>
     */
    com.google.protobuf.ByteString
        getFromIdBytes();

    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>optional string destId = 5;</code>
     */
    boolean hasDestId();
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>optional string destId = 5;</code>
     */
    java.lang.String getDestId();
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>optional string destId = 5;</code>
     */
    com.google.protobuf.ByteString
        getDestIdBytes();

    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 6;</code>
     */
    boolean hasCreateTime();
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 6;</code>
     */
    long getCreateTime();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .binary.wz.im.common.proto.InternalMsg.MsgType msgType = 7;</code>
     */
    boolean hasMsgType();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .binary.wz.im.common.proto.InternalMsg.MsgType msgType = 7;</code>
     */
    binary.wz.im.common.proto.Internal.InternalMsg.MsgType getMsgType();

    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 8;</code>
     */
    boolean hasMsgBody();
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 8;</code>
     */
    java.lang.String getMsgBody();
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 8;</code>
     */
    com.google.protobuf.ByteString
        getMsgBodyBytes();
  }
  /**
   * Protobuf type {@code binary.wz.im.common.proto.InternalMsg}
   */
  public  static final class InternalMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:binary.wz.im.common.proto.InternalMsg)
      InternalMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InternalMsg.newBuilder() to construct.
    private InternalMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InternalMsg() {
      id_ = "";
      fromId_ = "";
      destId_ = "";
      msgType_ = 0;
      msgBody_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InternalMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              id_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              seq_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              fromId_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              destId_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              createTime_ = input.readInt64();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              binary.wz.im.common.proto.Internal.InternalMsg.MsgType value = binary.wz.im.common.proto.Internal.InternalMsg.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                msgType_ = rawValue;
              }
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              msgBody_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return binary.wz.im.common.proto.Internal.internal_static_binary_wz_im_common_proto_InternalMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return binary.wz.im.common.proto.Internal.internal_static_binary_wz_im_common_proto_InternalMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              binary.wz.im.common.proto.Internal.InternalMsg.class, binary.wz.im.common.proto.Internal.InternalMsg.Builder.class);
    }

    /**
     * Protobuf enum {@code binary.wz.im.common.proto.InternalMsg.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GREET = 0;</code>
       */
      GREET(0),
      /**
       * <code>ACK = 1;</code>
       */
      ACK(1),
      /**
       * <code>ERROR = 2;</code>
       */
      ERROR(2),
      ;

      /**
       * <code>GREET = 0;</code>
       */
      public static final int GREET_VALUE = 0;
      /**
       * <code>ACK = 1;</code>
       */
      public static final int ACK_VALUE = 1;
      /**
       * <code>ERROR = 2;</code>
       */
      public static final int ERROR_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgType valueOf(int value) {
        return forNumber(value);
      }

      public static MsgType forNumber(int value) {
        switch (value) {
          case 0: return GREET;
          case 1: return ACK;
          case 2: return ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return binary.wz.im.common.proto.Internal.InternalMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:binary.wz.im.common.proto.InternalMsg.MsgType)
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <pre>
     *协议版本号
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *协议版本号
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     *消息标识
     * </pre>
     *
     * <code>required string id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *消息标识
     * </pre>
     *
     * <code>required string id = 2;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息标识
     * </pre>
     *
     * <code>required string id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQ_FIELD_NUMBER = 3;
    private long seq_;
    /**
     * <pre>
     *消息序号
     * </pre>
     *
     * <code>optional int64 seq = 3;</code>
     */
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *消息序号
     * </pre>
     *
     * <code>optional int64 seq = 3;</code>
     */
    public long getSeq() {
      return seq_;
    }

    public static final int FROMID_FIELD_NUMBER = 4;
    private volatile java.lang.Object fromId_;
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>optional string fromId = 4;</code>
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>optional string fromId = 4;</code>
     */
    public java.lang.String getFromId() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>optional string fromId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTID_FIELD_NUMBER = 5;
    private volatile java.lang.Object destId_;
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>optional string destId = 5;</code>
     */
    public boolean hasDestId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>optional string destId = 5;</code>
     */
    public java.lang.String getDestId() {
      java.lang.Object ref = destId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>optional string destId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDestIdBytes() {
      java.lang.Object ref = destId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 6;
    private long createTime_;
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 6;</code>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 6;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 7;
    private int msgType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .binary.wz.im.common.proto.InternalMsg.MsgType msgType = 7;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .binary.wz.im.common.proto.InternalMsg.MsgType msgType = 7;</code>
     */
    public binary.wz.im.common.proto.Internal.InternalMsg.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      binary.wz.im.common.proto.Internal.InternalMsg.MsgType result = binary.wz.im.common.proto.Internal.InternalMsg.MsgType.valueOf(msgType_);
      return result == null ? binary.wz.im.common.proto.Internal.InternalMsg.MsgType.GREET : result;
    }

    public static final int MSGBODY_FIELD_NUMBER = 8;
    private volatile java.lang.Object msgBody_;
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 8;</code>
     */
    public boolean hasMsgBody() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 8;</code>
     */
    public java.lang.String getMsgBody() {
      java.lang.Object ref = msgBody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgBody_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBodyBytes() {
      java.lang.Object ref = msgBody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, seq_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, destId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt64(6, createTime_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeEnum(7, msgType_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, msgBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, seq_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, destId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createTime_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, msgType_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, msgBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof binary.wz.im.common.proto.Internal.InternalMsg)) {
        return super.equals(obj);
      }
      binary.wz.im.common.proto.Internal.InternalMsg other = (binary.wz.im.common.proto.Internal.InternalMsg) obj;

      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (!getId()
            .equals(other.getId())) return false;
      }
      if (hasSeq() != other.hasSeq()) return false;
      if (hasSeq()) {
        if (getSeq()
            != other.getSeq()) return false;
      }
      if (hasFromId() != other.hasFromId()) return false;
      if (hasFromId()) {
        if (!getFromId()
            .equals(other.getFromId())) return false;
      }
      if (hasDestId() != other.hasDestId()) return false;
      if (hasDestId()) {
        if (!getDestId()
            .equals(other.getDestId())) return false;
      }
      if (hasCreateTime() != other.hasCreateTime()) return false;
      if (hasCreateTime()) {
        if (getCreateTime()
            != other.getCreateTime()) return false;
      }
      if (hasMsgType() != other.hasMsgType()) return false;
      if (hasMsgType()) {
        if (msgType_ != other.msgType_) return false;
      }
      if (hasMsgBody() != other.hasMsgBody()) return false;
      if (hasMsgBody()) {
        if (!getMsgBody()
            .equals(other.getMsgBody())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasSeq()) {
        hash = (37 * hash) + SEQ_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSeq());
      }
      if (hasFromId()) {
        hash = (37 * hash) + FROMID_FIELD_NUMBER;
        hash = (53 * hash) + getFromId().hashCode();
      }
      if (hasDestId()) {
        hash = (37 * hash) + DESTID_FIELD_NUMBER;
        hash = (53 * hash) + getDestId().hashCode();
      }
      if (hasCreateTime()) {
        hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCreateTime());
      }
      if (hasMsgType()) {
        hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + msgType_;
      }
      if (hasMsgBody()) {
        hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
        hash = (53 * hash) + getMsgBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static binary.wz.im.common.proto.Internal.InternalMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static binary.wz.im.common.proto.Internal.InternalMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static binary.wz.im.common.proto.Internal.InternalMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static binary.wz.im.common.proto.Internal.InternalMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static binary.wz.im.common.proto.Internal.InternalMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static binary.wz.im.common.proto.Internal.InternalMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static binary.wz.im.common.proto.Internal.InternalMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static binary.wz.im.common.proto.Internal.InternalMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static binary.wz.im.common.proto.Internal.InternalMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static binary.wz.im.common.proto.Internal.InternalMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static binary.wz.im.common.proto.Internal.InternalMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static binary.wz.im.common.proto.Internal.InternalMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(binary.wz.im.common.proto.Internal.InternalMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code binary.wz.im.common.proto.InternalMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:binary.wz.im.common.proto.InternalMsg)
        binary.wz.im.common.proto.Internal.InternalMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return binary.wz.im.common.proto.Internal.internal_static_binary_wz_im_common_proto_InternalMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return binary.wz.im.common.proto.Internal.internal_static_binary_wz_im_common_proto_InternalMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                binary.wz.im.common.proto.Internal.InternalMsg.class, binary.wz.im.common.proto.Internal.InternalMsg.Builder.class);
      }

      // Construct using binary.wz.im.common.proto.Internal.InternalMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        seq_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        fromId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        destId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        msgBody_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return binary.wz.im.common.proto.Internal.internal_static_binary_wz_im_common_proto_InternalMsg_descriptor;
      }

      @java.lang.Override
      public binary.wz.im.common.proto.Internal.InternalMsg getDefaultInstanceForType() {
        return binary.wz.im.common.proto.Internal.InternalMsg.getDefaultInstance();
      }

      @java.lang.Override
      public binary.wz.im.common.proto.Internal.InternalMsg build() {
        binary.wz.im.common.proto.Internal.InternalMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public binary.wz.im.common.proto.Internal.InternalMsg buildPartial() {
        binary.wz.im.common.proto.Internal.InternalMsg result = new binary.wz.im.common.proto.Internal.InternalMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.seq_ = seq_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fromId_ = fromId_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.destId_ = destId_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.createTime_ = createTime_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000080) != 0)) {
          to_bitField0_ |= 0x00000080;
        }
        result.msgBody_ = msgBody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof binary.wz.im.common.proto.Internal.InternalMsg) {
          return mergeFrom((binary.wz.im.common.proto.Internal.InternalMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(binary.wz.im.common.proto.Internal.InternalMsg other) {
        if (other == binary.wz.im.common.proto.Internal.InternalMsg.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000002;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        if (other.hasFromId()) {
          bitField0_ |= 0x00000008;
          fromId_ = other.fromId_;
          onChanged();
        }
        if (other.hasDestId()) {
          bitField0_ |= 0x00000010;
          destId_ = other.destId_;
          onChanged();
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasMsgBody()) {
          bitField0_ |= 0x00000080;
          msgBody_ = other.msgBody_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasVersion()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        if (!hasCreateTime()) {
          return false;
        }
        if (!hasMsgType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        binary.wz.im.common.proto.Internal.InternalMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (binary.wz.im.common.proto.Internal.InternalMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <pre>
       *协议版本号
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *协议版本号
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       *协议版本号
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协议版本号
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <pre>
       *消息标识
       * </pre>
       *
       * <code>required string id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *消息标识
       * </pre>
       *
       * <code>required string id = 2;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息标识
       * </pre>
       *
       * <code>required string id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息标识
       * </pre>
       *
       * <code>required string id = 2;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息标识
       * </pre>
       *
       * <code>required string id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息标识
       * </pre>
       *
       * <code>required string id = 2;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }

      private long seq_ ;
      /**
       * <pre>
       *消息序号
       * </pre>
       *
       * <code>optional int64 seq = 3;</code>
       */
      public boolean hasSeq() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *消息序号
       * </pre>
       *
       * <code>optional int64 seq = 3;</code>
       */
      public long getSeq() {
        return seq_;
      }
      /**
       * <pre>
       *消息序号
       * </pre>
       *
       * <code>optional int64 seq = 3;</code>
       */
      public Builder setSeq(long value) {
        bitField0_ |= 0x00000004;
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息序号
       * </pre>
       *
       * <code>optional int64 seq = 3;</code>
       */
      public Builder clearSeq() {
        bitField0_ = (bitField0_ & ~0x00000004);
        seq_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object fromId_ = "";
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>optional string fromId = 4;</code>
       */
      public boolean hasFromId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>optional string fromId = 4;</code>
       */
      public java.lang.String getFromId() {
        java.lang.Object ref = fromId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fromId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>optional string fromId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFromIdBytes() {
        java.lang.Object ref = fromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>optional string fromId = 4;</code>
       */
      public Builder setFromId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>optional string fromId = 4;</code>
       */
      public Builder clearFromId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fromId_ = getDefaultInstance().getFromId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>optional string fromId = 4;</code>
       */
      public Builder setFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fromId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object destId_ = "";
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>optional string destId = 5;</code>
       */
      public boolean hasDestId() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>optional string destId = 5;</code>
       */
      public java.lang.String getDestId() {
        java.lang.Object ref = destId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            destId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>optional string destId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDestIdBytes() {
        java.lang.Object ref = destId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>optional string destId = 5;</code>
       */
      public Builder setDestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        destId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>optional string destId = 5;</code>
       */
      public Builder clearDestId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        destId_ = getDefaultInstance().getDestId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>optional string destId = 5;</code>
       */
      public Builder setDestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        destId_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 6;</code>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 6;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 6;</code>
       */
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000020;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 6;</code>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .binary.wz.im.common.proto.InternalMsg.MsgType msgType = 7;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .binary.wz.im.common.proto.InternalMsg.MsgType msgType = 7;</code>
       */
      public binary.wz.im.common.proto.Internal.InternalMsg.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        binary.wz.im.common.proto.Internal.InternalMsg.MsgType result = binary.wz.im.common.proto.Internal.InternalMsg.MsgType.valueOf(msgType_);
        return result == null ? binary.wz.im.common.proto.Internal.InternalMsg.MsgType.GREET : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .binary.wz.im.common.proto.InternalMsg.MsgType msgType = 7;</code>
       */
      public Builder setMsgType(binary.wz.im.common.proto.Internal.InternalMsg.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .binary.wz.im.common.proto.InternalMsg.MsgType msgType = 7;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msgBody_ = "";
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 8;</code>
       */
      public boolean hasMsgBody() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 8;</code>
       */
      public java.lang.String getMsgBody() {
        java.lang.Object ref = msgBody_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgBody_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 8;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBodyBytes() {
        java.lang.Object ref = msgBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 8;</code>
       */
      public Builder setMsgBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        msgBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 8;</code>
       */
      public Builder clearMsgBody() {
        bitField0_ = (bitField0_ & ~0x00000080);
        msgBody_ = getDefaultInstance().getMsgBody();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 8;</code>
       */
      public Builder setMsgBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        msgBody_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:binary.wz.im.common.proto.InternalMsg)
    }

    // @@protoc_insertion_point(class_scope:binary.wz.im.common.proto.InternalMsg)
    private static final binary.wz.im.common.proto.Internal.InternalMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new binary.wz.im.common.proto.Internal.InternalMsg();
    }

    public static binary.wz.im.common.proto.Internal.InternalMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<InternalMsg>
        PARSER = new com.google.protobuf.AbstractParser<InternalMsg>() {
      @java.lang.Override
      public InternalMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InternalMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InternalMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InternalMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public binary.wz.im.common.proto.Internal.InternalMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_binary_wz_im_common_proto_InternalMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_binary_wz_im_common_proto_InternalMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'src/main/resources/proto/Internal.prot" +
      "o\022\031binary.wz.im.common.proto\"\347\001\n\013Interna" +
      "lMsg\022\017\n\007version\030\001 \002(\005\022\n\n\002id\030\002 \002(\t\022\013\n\003seq" +
      "\030\003 \001(\003\022\016\n\006fromId\030\004 \001(\t\022\016\n\006destId\030\005 \001(\t\022\022" +
      "\n\ncreateTime\030\006 \002(\003\022?\n\007msgType\030\007 \002(\0162..bi" +
      "nary.wz.im.common.proto.InternalMsg.MsgT" +
      "ype\022\017\n\007msgBody\030\010 \001(\t\"(\n\007MsgType\022\t\n\005GREET" +
      "\020\000\022\007\n\003ACK\020\001\022\t\n\005ERROR\020\002B\nB\010Internal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_binary_wz_im_common_proto_InternalMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_binary_wz_im_common_proto_InternalMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_binary_wz_im_common_proto_InternalMsg_descriptor,
        new java.lang.String[] { "Version", "Id", "Seq", "FromId", "DestId", "CreateTime", "MsgType", "MsgBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
